"""added bmi column in weight table

Revision ID: 527d05bdc9ce
Revises: 9ab257a296bc
Create Date: 2020-08-20 16:54:42.552257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527d05bdc9ce'
down_revision = '9ab257a296bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight', sa.Column('bmi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weight', 'bmi')
    # ### end Alembic commands ###
