"""added lenght column to user table

Revision ID: 9ab257a296bc
Revises: 1fa86671b996
Create Date: 2020-08-20 15:38:30.345214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab257a296bc'
down_revision = '1fa86671b996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'length')
    # ### end Alembic commands ###
